<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Internal staff chat: a per-clinic group channel + 1:1 direct conversations
 * between clinic staff, and cross-clinic 1:1 DMs between the platform super
 * admin and any staff member (stored under the staff member's clinic_id so the
 * staff side sees it via RLS and the super admin via the fn_is_super_admin()
 * bypass). Clinic-scoped with the standard tenant_isolation RLS (declared
 * inline here rather than in the catch-all RLS migration, which has already
 * run on existing databases).
 *
 * `messages.sender_name` and `conversation_participants.display_name` are
 * denormalized at write time so the UI can render a counterpart's name without
 * joining `users` — which still enforces tenant_isolation, so a staff member
 * cannot read the platform super admin's user row across the clinic boundary.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE conversations (
                id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                clinic_id        UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
                type             VARCHAR(20) NOT NULL CHECK (type IN ('direct', 'clinic')),
                dedupe_key       VARCHAR(100) NOT NULL,
                last_message_at  TIMESTAMPTZ,
                created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (clinic_id, dedupe_key)
            )
        SQL);

        DB::statement(<<<'SQL'
            CREATE TABLE conversation_participants (
                id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                clinic_id        UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
                conversation_id  UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                display_name     VARCHAR(200),
                last_read_at     TIMESTAMPTZ,
                created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (conversation_id, user_id)
            )
        SQL);
        DB::statement('CREATE INDEX idx_conversation_participants_user ON conversation_participants(user_id)');

        DB::statement(<<<'SQL'
            CREATE TABLE messages (
                id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                clinic_id        UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
                conversation_id  UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                sender_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                sender_name      VARCHAR(200),
                body             TEXT NOT NULL,
                seq              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        SQL);
        // `seq` is the monotonic ordering key: random UUID ids give no order and
        // created_at is only second-precision once Eloquent serializes it, so
        // ordering + the polling "after" cursor both key off seq instead.
        DB::statement('CREATE INDEX idx_messages_conversation_seq ON messages(conversation_id, seq)');

        foreach (['conversations', 'conversation_participants', 'messages'] as $table) {
            DB::statement("ALTER TABLE {$table} ENABLE ROW LEVEL SECURITY");
            DB::statement("ALTER TABLE {$table} FORCE ROW LEVEL SECURITY");
            DB::statement(<<<SQL
                CREATE POLICY tenant_isolation ON {$table}
                    FOR ALL
                    USING (fn_is_super_admin() OR clinic_id = fn_current_clinic_id())
                    WITH CHECK (fn_is_super_admin() OR clinic_id = fn_current_clinic_id())
            SQL);
        }
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS messages CASCADE');
        DB::statement('DROP TABLE IF EXISTS conversation_participants CASCADE');
        DB::statement('DROP TABLE IF EXISTS conversations CASCADE');
    }
};
